{
  "hash": "cf65155a4f1ffcb43c655bd2cb63e134",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"2024 US Men's Gymnastics Olympic Team Selection\"\nauthor: \"Dante Yasui\"\ndate: \"2024/06/29\"\nformat:\n  html:\n    df-print: kable\n    toc: true\n---\n\n\n\n# TODO\n\n- Calculate what the other top team compositions were\n  - [x] apply [@lst-functions] to each possible team combo \n  and select the max scoring team based on the averages in [@lst-data]\n- [x] visualize the relative strengths of the team by comparing against distributions in [@fig-eventdist]\n- [ ] compare to similar scores of other national teams\n- [ ] make events print in olympic order, not alphabetic\n- [ ] calculate each team members contribution by picking best team \nwhen they are dropped from results dataset\n\n---\n\n# Data\n\nI copied the data from <https://myusagym.com>\nand manually cleaned it up into `.csv` format.\n\n\n\n::: {.cell}\n\n```{#lst-data .r .cell-code  lst-cap=\"combining data from nationals and trials\"}\nlibrary(tidyverse)\n# read all results across usa champs and olympic trials\nnc1_df <- read_csv(\"./natnls-d1.csv\")\nnc2_df <- read_csv(\"./natnls-d2.csv\")\not1_df <- read_csv(\"./trials-day1.csv\")\not2_df <- read_csv(\"./trials-day2.csv\")\n# merge all results into one dataframe\nresults_df <- bind_rows(list(nc1_df, nc2_df, ot1_df, ot2_df))\n```\n:::\n\n\n\nTo visualize the data overall, \nI grouped scores by event from all USA Championships and Olympic Trials \nroutines and plotted the spread of observed scores.\n\n\n\n::: {.cell}\n\n```{#lst-eventdist .r .cell-code  lst-cap=\"plot of event distributions\"}\nlibrary(ggthemes)\neventsdist <- results_df %>% select(!AA) %>%\n  pivot_longer(\n    cols = c(FX, PH, SR, VT, PB, HB),\n    names_to = \"Event\",\n    values_to = \"Score\",\n  ) %>% filter(Score > 1) %>%\n  ggplot(aes(x=Score)) +\n  geom_density() +\n  xlim(11, 16) +\n  facet_wrap(~Event, ncol = 2) +\n  theme_pander()\neventsdist\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 9 rows containing non-finite outside the scale range\n(`stat_density()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![national distributions of scores on each event](analysis_files/figure-html/fig-eventdist-1.png){#fig-eventdist width=672}\n:::\n:::\n\n\n\nNot surprisingly, out of all six event Pommel has the largest variance in\nscores and the lowest average.\nP-Bars and Vault are high-scoring events on average but Vault \n(at least for these competitions) is more consistently grouped around 14\nwhile the P-Bars distribution seem to have a large right tail \nwith a lot of potential for 15+ scores.\n\n## Averages across usa championships and olympic trials\n\n\n\n::: {#tbl-averagescores .cell tbl-cap='Individuals\\' average scores across nationals and trials'}\n\n```{.r .cell-code}\n# average individual gymnasts' scores across four days\nindv.averages_df <- results_df %>% \n  filter(NAME %in% ot1_df$NAME) %>%  # who qualified to olympic trials \n  group_by(NAME) %>% \n  summarise_at(vars(FX:AA), mean, na.rm=TRUE) %>% \n  arrange(desc(AA))\nindv.averages_df\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|NAME                |      FX|       PH|      SR|       VT|       PB|      HB|      AA|\n|:-------------------|-------:|--------:|-------:|--------:|--------:|-------:|-------:|\n|Brody Malone        | 13.9250| 13.87500| 14.4500| 14.42500| 14.73750| 14.2375| 85.6500|\n|Fred Richard        | 14.5500| 13.30000| 13.9875| 14.25000| 14.68750| 14.4125| 85.1875|\n|Shane Wiskus        | 14.3875| 13.63750| 13.8375| 14.37500| 14.61250| 13.6125| 84.4625|\n|Paul Juda           | 14.3250| 14.05000| 13.8875| 14.28750| 14.02500| 13.4250| 84.0000|\n|Yul Moldauer        | 14.3000| 13.06250| 13.9375| 13.95000| 15.01250| 13.1125| 83.3750|\n|Donnell Whittenburg | 14.1750| 12.88750| 14.4250| 14.41250| 14.30000| 12.9750| 83.1750|\n|Asher Hong          | 13.9750| 12.31250| 14.5500| 14.53750| 14.76250| 13.0250| 83.1625|\n|Cameron Bock        | 13.7375| 13.97500| 13.7750| 13.75000| 14.22500| 13.6500| 83.1125|\n|Fuzzy Benas         | 13.9875| 13.70000| 13.5375| 13.86250| 14.07500| 13.4625| 82.6250|\n|Colt Walker         | 13.5625| 13.66250| 13.7375| 14.06250| 14.86250| 12.6125| 82.5000|\n|Jeremy Bischoff     | 13.6875| 13.21250| 13.3375| 13.83750| 13.77500| 13.2375| 81.0875|\n|Khoi Young          | 14.0875| 13.37500|  9.9500| 14.92500| 14.68750| 13.1625| 80.1875|\n|Joshua Karnes       | 12.9750| 12.93750| 13.2250| 12.20000| 14.46250| 13.1500| 78.7250|\n|Kiran Mandava       | 13.0500| 12.40000| 12.8750| 13.72500| 13.47500| 12.7000| 78.2250|\n|Kai Uemura          | 12.9625| 11.57500| 12.9125| 13.30000| 13.25000| 12.8125| 76.8125|\n|Tate Costa          | 12.6125| 10.98755| 11.9375| 13.52500| 12.80000| 12.5500| 74.4125|\n|Alex Diab           |     NaN|      NaN| 14.6250|      NaN|      NaN|     NaN|     NaN|\n|Curran Phillips     | 13.0000|      NaN|     NaN| 13.66667| 15.58333| 13.2000|     NaN|\n|Patrick Hoopes      |     NaN| 14.67500|     NaN|      NaN|      NaN|     NaN|     NaN|\n|Stephen Nedoroscik  |     NaN| 14.82500|     NaN|      NaN|      NaN|     NaN|     NaN|\n\n</div>\n:::\n:::\n\n\n\n---\n\n## Predicting a Team's performance\n\n\n::: {.cell}\n\n```{#lst-functions .r .cell-code  lst-cap=\"functions for calculating team performance\"}\n# function to pick top three scores on each event from a team\nteam_top_scores <- function(names, scores = indv.averages_df, perevent = 3) {\n  scores %>% \n    filter(NAME %in% names) %>%\n    select(-AA) %>% \n    pivot_longer(\n      -NAME,\n      names_to = \"Event\",\n      values_to = \"Score\",\n    ) %>% \n    # take top 3 on each event dropping extra tied scores\n    group_by(Event) %>% \n    slice_max(n = perevent, order_by = Score, with_ties = FALSE) %>% \n    mutate(\n      teamscore = sum(Score),\n      # names     = c(unique(NAME))\n      )  %>%\n    group_by(Event) %>% \n    summarise(\n      Score   = first(teamscore),\n      OnEvent = list((NAME))\n      ) %>% ungroup()\n}\n\n# function to take output of select_top_scores and calculate total\nteam_total <- function(top_scores) {\n  top_scores %>% \n    summarise(x=sum(Score)) %>% \n    pull()\n}\n```\n:::\n\n\n\nThis method assumes that scores earned at the USA Championships and Olympic\nTrials are accurate predictions of scores earned at the actual Olympics.\nThese will be over-estimates of a potential team's Olympic performance if the \ndomestic judging is less strict than the Olympic Committee judges panels.\n\nMy code also implicitly uses a 5-up, 3-count scoring system which is different\nfrom the actual 3-up, 3-count rule during Olympic team finals.\nWhile the US might choose the lineup in this way, they will also probably \nhave to take into account the health of their athletes\n(e.g., resting Brody's leg by not having him vault).\n\n# Team USA's expected performance\n\n## Event scores breakdown\n\n\n::: {#tbl-teamevents .cell tbl-cap='Team USA expected event scores'}\n\n```{#lst-actualteam .r .cell-code  lst-cap=\"team_top_scores() of actual team picks\"}\nteam_names <- c(\"Brody Malone\", \"Fred Richard\", \"Asher Hong\", \"Paul Juda\",\n                \"Stephen Nedoroscik\")\nactual_team <- team_top_scores(team_names)\nactual_team_tot <- actual_team %>% \n  team_total()\nactual_team\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Event |   Score|OnEvent                                              |\n|:-----|-------:|:----------------------------------------------------|\n|FX    | 42.8500|Fred Richard, Paul Juda   , Asher Hong               |\n|HB    | 42.0750|Fred Richard, Brody Malone, Paul Juda                |\n|PB    | 44.1875|Asher Hong  , Brody Malone, Fred Richard             |\n|PH    | 42.7500|Stephen Nedoroscik, Paul Juda         , Brody Malone |\n|SR    | 42.9875|Asher Hong  , Brody Malone, Fred Richard             |\n|VT    | 43.2500|Asher Hong  , Brody Malone, Paul Juda                |\n\n</div>\n:::\n:::\n\n\n\n### Interpreting the team's average scores\n\nThe expected team score for this team ^[with domestic judging]\nis 258.1.\nFor some context, the gold medal Japanese team at 2023 world championships\n^[according to the [wikipedia page](https://en.m.wikipedia.org/wiki/2023_World_Artistic_Gymnastics_Championships)]\nscored 255.594 and USA won bronze at the same competition with 252.428.\n\nOn paper this teams strengths relative to international competition seem to be\nFloor, Pommel, and High Bar with scores of \n42.85,\n42.75, and\n42.075,\nrespectively.\nHowever, the US is pretty infamous for not being able to pull together their \nfull potential on Pommel.\n\nThis team also remains competitive on  Rings with an average score of \n42.9875\nand on P-Bars with a\n44.1875.\nWith China being so dominant on those two events they probably won't win any\nevent final medals there but having those two events as strengths will definitely help the team score against Japan and Great Britain.\n\nIt's kind of surprising that the main weakness on paper of this team is vault.\nWith Brody, Paul, and Asher vaulting at a total predicted score of \n43.25,\nthey fall behind both China's and Great Britain's scores as well as the \nprevious US team's own score on the event from last year.\nI heard that judging on Asher's Ri Se Gwang vault seemed overly harsh,\nso it's possible that this team vault score gets better,\nbut I think he's the only one with a D-score higher than 5.6 on this event.\n\n### Potential vs Expectations\n\nThere will also be more psychological strain on these athletes which comes with\nthe media attention and unfamiliar setting in Paris.\nThis could be a factor that could potentially affect this team more than other\nalternative US teams.\n\nI was hoping that Yul Muldauer could provide the same kind of leadership\nhe showed at the World Championships to a younger and less-internationally \nexperienced team.\nUnfortunately he didn't perform up to his usual level of execution and \nconsistency in these past few competitions so I understand why he was left off.\nThese five guys (with maybe the exception of Paul?) have experience competing\nat the World/Olympic level, but I think Yul is one of those guys who gets along\nwith everyone and feels comfortable in the spotlight.\nI think Fred has a very similar enthusiasm and drive, but this is still only \nhis second year of competing at the senior international level.\n\nThe first night of the Olympic Trials made me pretty nervous about the \nability for US gymnasts to stay consistent with increased attention on them.\nIt was great to see how full the stadium in Minneapolis was for men's gymnastics,\nbut I also thought that some of the extra shakiness on Pommel and throughout the night might have been attributable to all the extra energy around.\nThis team has a lot of potential and I just hope that they don't get \noverwhelmed by the pressure of thinking that they need to live up to the \nhigh expectations of a domestic audience who only tune in every four years\nwith the anticipation that anything team USA touches at the Olympics could turn to gold.\n\n### Comparing to the rest of the field\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteam_scores <- indv.averages_df %>% \n    filter(NAME %in% team_names) %>%\n    select(-AA) %>% \n    pivot_longer(\n      -NAME,\n      names_to = \"Event\",\n      values_to = \"Score\",\n    )\neventsdist +\n  geom_vline(\n    data = team_scores, \n    aes(\n      xintercept = Score, \n      color = Score,\n      ),\n      linetype = \"dashed\"\n    ) +\n  geom_text(\n    data = team_scores, \n    aes(\n      y = 0.4,\n      x = Score,\n      label = NAME,\n      color = Score\n      ),\n    angle = 270,\n    size = 2,\n    nudge_x = 0.05,\n    ) +\n  scale_color_viridis_c(option = \"turbo\", direction = -1) +\n  xlim(12, 15)\n```\n\n::: {.cell-output-display}\n![Olympic team's scores relative to everyone else](analysis_files/figure-html/fig-eventdist_team-1.png){#fig-eventdist_team width=672}\n:::\n:::\n\n\n\n---\n\n# Team Selection Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames <- indv.averages_df %>% select(NAME) %>% pull()\n\n# all combinations of gymnasts choosing five at a time\nteams_possible <- combinat::combn(names, 5, simplify = T) %>% \n  as_tibble() %>% \n  pivot_longer(\n    cols = everything(),\n    names_to = \"team\",\n    values_to = \"name\") %>% \n  group_by(team) %>% \n  summarise(\n    names = list(name)\n  )\n\n# function to apply team_total to list of names\nteam_top_total <- function(x) team_total(team_top_scores(unlist(x)))\n\n# record top scores for every possible team combination\nteamsim_df <- teams_possible %>% \n  mutate(\n    total = as.numeric(map(names, team_top_total)),\n    # names = map(names, toString)\n  ) %>% \n  arrange(desc(total))\n\n# save sim results to file\nsave(teamsim_df, file = \"teamsim.RData\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nspecialist_rule <- function(teams, individuals) {\n  specialists <- individuals %>% \n    filter(is.na(AA)) %>% \n    select(NAME) %>% \n    pull()\n  teams %>% \n    filter(\n      str_count(.$names, paste(specialists, collapse='|')) < 2\n    )\n}\n```\n:::\n\n::: {#tbl-topteams .cell tbl-cap='Top ten scoring teams on average'}\n\n```{.r .cell-code}\nload(\"./teamsim.RData\")\nteamsim_df %>% \n  select(-team) %>% \n  filter(str_detect(.$names, \"Patrick Hoopes\", negate = T)) %>% \n  specialist_rule(individuals = indv.averages_df) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `filter()`.\nℹ In argument: `str_detect(.$names, \"Patrick Hoopes\", negate = T)`.\nCaused by warning in `stri_detect_regex()`:\n! argument is not an atomic vector; coercing\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `filter()`.\nℹ In argument: `str_count(.$names, paste(specialists, collapse = \"|\")) < 2`.\nCaused by warning in `stri_count_regex()`:\n! argument is not an atomic vector; coercing\n```\n\n\n:::\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|names                                                                                                  |    total|\n|:------------------------------------------------------------------------------------------------------|--------:|\n|Brody Malone      , Fred Richard      , Paul Juda         , Asher Hong        , Stephen Nedoroscik     | 258.1000|\n|Brody Malone      , Fred Richard      , Shane Wiskus      , Asher Hong        , Stephen Nedoroscik     | 258.0250|\n|Brody Malone      , Fred Richard      , Paul Juda         , Khoi Young        , Stephen Nedoroscik     | 257.8625|\n|Brody Malone       , Fred Richard       , Shane Wiskus       , Donnell Whittenburg, Stephen Nedoroscik | 257.8250|\n|Brody Malone      , Fred Richard      , Asher Hong        , Cameron Bock      , Stephen Nedoroscik     | 257.8125|\n|Brody Malone      , Fred Richard      , Paul Juda         , Yul Moldauer      , Stephen Nedoroscik     | 257.7750|\n|Brody Malone      , Fred Richard      , Shane Wiskus      , Khoi Young        , Stephen Nedoroscik     | 257.7375|\n|Brody Malone      , Fred Richard      , Shane Wiskus      , Paul Juda         , Stephen Nedoroscik     | 257.7250|\n|Brody Malone      , Fred Richard      , Shane Wiskus      , Yul Moldauer      , Stephen Nedoroscik     | 257.7000|\n|Brody Malone, Fred Richard, Shane Wiskus, Paul Juda   , Asher Hong                                     | 257.6000|\n\n</div>\n:::\n:::\n\n\n\nIt's not surprising that Brody and Fred show up on all of these teams.\nAsher is also pretty dominant in this ranking, which seems to be coming from his\nhigher performances on rings and p-bars compared to Donnell and being close\nenough to Khoi on vault and floor.\n\nThe top team of all all-arounders just swaps out Stephen for Shane \nand scores more than a point lower.\nInteresting that Yul has a better all-around average than Asher, \nand yet he wouldn't actually the better pick in an all all-arounder team.\nA lot of these teams are just variations of the same teams except swapping \nStephen and Patrick Hoopes.\nBecause Stephen had a higher four-score average and potential difficulty \nthan Patrick, I drop Patrick from the list to get a sense of some more \nrealistic alternate team selections.\n\nThis also highlights how close Shane came to being on the team (by just .75)! \nBut it also how similar his contributions are to Paul's which sort of put him\nin the same unfortunate position as Patrick Hoopes who's status as a pommel \nspecialist means that he can only really be swapped out with Stephen.\n\n### Importance of Pommel Horse Specialists\n\nOne thing I didn't expect before seeing these simulated teams\nis that almost all of these top 20 teams have at least one pommel specialist\n(before I dropped Patrick).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPH_actual_team <- actual_team %>% filter(Event==\"PH\") %>% \n  select(Score) %>% pull()\nPH_second_best <- indv.averages_df %>% \n  filter(!is.na(AA)) %>% \n  select(NAME, PH) %>% \n  slice_max(order_by = PH, n = 3)\nPH_second_best\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|NAME         |     PH|\n|:------------|------:|\n|Paul Juda    | 14.050|\n|Cameron Bock | 13.975|\n|Brody Malone | 13.875|\n\n</div>\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\nWithout sending a pommel horse specialist to Paris, \nthe best possible team score USA could put up on this event would be \n41.9.\nSo Stephen is contributing at least an extra \n0.85 points to the team score\nand likely more considering that he's making sure Fred's 13.3 PH average \nwon't have to be counted. \n\n\n\n::: {.cell}\n\n:::\n\n\n\nIf Khoi had hit his pommel routines consistently then he would have seemed\nlike a much more obvious replacement for Stephen because he has the potential\nto put up a 15.0 like he showed in night 2 of US Championships.\nHe would also make the team's vault score a lot more competitive where his \naverage score of \n14.925 is actually \n4\ntenths higher than Asher's and seems to be a lot more consistent.\n\n# Other hypothetical compositions\n\n### Picking only the top all-arounders\n\n\n::: {#tbl-altteam1events .cell tbl-cap='Top 5 all-arounders team event scores'}\n\n```{.r .cell-code}\n# If they had taken top five all arounders\nalt_team1_names <- indv.averages_df %>% \n  slice_head(n=5) %>% \n  select(NAME) %>% \n  pull()\nalt_team1 <- team_top_scores(alt_team1_names)\nalt_team1\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Event |   Score|OnEvent                                  |\n|:-----|-------:|:----------------------------------------|\n|FX    | 43.2625|Fred Richard, Shane Wiskus, Paul Juda    |\n|HB    | 42.2625|Fred Richard, Brody Malone, Shane Wiskus |\n|PB    | 44.4375|Yul Moldauer, Brody Malone, Fred Richard |\n|PH    | 41.5625|Paul Juda   , Brody Malone, Shane Wiskus |\n|SR    | 42.3750|Brody Malone, Fred Richard, Yul Moldauer |\n|VT    | 43.0875|Brody Malone, Shane Wiskus, Paul Juda    |\n\n</div>\n:::\n:::\n\n\n\nThis team has an expected score of 256.9875 \nwhich is 1.1 points \nbehind the selected team's expected score,\nso it makes sense they didn't go with this team.\nPaul and Shane are both similar in that their main strengths are contributing \nsolid performances on any event but neither have any standout routines with\nenough difficulty to put them in event finals. \nIt makes sense to have one gymnast fill this roll on a team, \nbut I don't think it makes sense to leave behind world-class routines like \nStephen's pommel horse or Asher's, Khoi's, or Donnell's vaults to gain\nthe additional safe scores from sending both Paul and Shane together.\n\nIt was really cool to see how hyped the Minneapolis crowd was to see \nshane compete in his hometown and he did a great job over the two nights there,\nbut ultimately Paul just put on a more consistent performance during \nUS Championships. \nAnd that's what this type of role on team USA is all about;\njust proving that you will put up a decent score every time you go up.\n\n### My team picks\n\n\n::: {#tbl-altteam2events .cell tbl-cap='My custom team\\'s event breakdown'}\n\n```{.r .cell-code}\n# My own personal picks\nalt_team2_names <- c(\"Fred Richard\", \"Brody Malone\", \"Yul Moldauer\", \"Donnell Whittenburg\", \"Khoi Young\")\nalt_team2 <- team_top_scores(alt_team2_names)\nalt_team2\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Event |   Score|OnEvent                                                       |\n|:-----|-------:|:-------------------------------------------------------------|\n|FX    | 43.0250|Fred Richard       , Yul Moldauer       , Donnell Whittenburg |\n|HB    | 41.8125|Fred Richard, Brody Malone, Khoi Young                        |\n|PB    | 44.4375|Yul Moldauer, Brody Malone, Fred Richard                      |\n|PH    | 40.5500|Brody Malone, Khoi Young  , Fred Richard                      |\n|SR    | 42.8625|Brody Malone       , Donnell Whittenburg, Fred Richard        |\n|VT    | 43.7625|Khoi Young         , Brody Malone       , Donnell Whittenburg |\n\n</div>\n:::\n:::\n\n\n\nThis team falls short by 1.7 points\nalthough I think they would have more opporunities to make event finals \non Floor, P-Bars, and Vault.\nGiven Donnell's vs Asher's performances over Nationals and Trials,\nit probably makes more sense to have Asher \nbut I think Donnell has more international experience \nand I also just really wanted to see him get to represent USA at the Olympics\nafter working so hard for his entire career and not really getting that much recognition.",
    "supporting": [
      "analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}